export type ErrorCodeType =
  | 'not_authorized'
  | 'session_not_initialized'
  | 'bad_request'
  | 'backend_error'
  | 'auth_error'
  | 'runtime_error'
  | 'illegal_dict_word'
  | 'timeout'
  | 'cannot_find_synonym'
  | 'cannot_get_text_stats'
