export const GRAMMARLY_SDK = Symbol('GrammarlySDK')
export const CLIENT = Symbol('ClientCapabilities')
export const CLIENT_INFO = Symbol('ClientInfo')
export const SERVER = Symbol('ServerCapabilities')
export const CONNECTION = Symbol('Connection')
