export const GRAMMARLY_SDK = Symbol('GrammarlySDK')
export const TEXT_DOCUMENTS_FACTORY = Symbol('TextDocuments')
export const CLIENT = Symbol('ClientCapabilities')
export const CLIENT_INFO = Symbol('ClientInfo')
export const CLIENT_INITIALIZATION_OPTIONS = Symbol('ClientInitializationOptions')
export const SERVER = Symbol('ServerCapabilities')
export const CONNECTION = Symbol('Connection')
